name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout/@v2

      - name: Setup node
        uses: actions/setup-node/@v2
        with: 
          node-version: "14"

      - name: Install
        env: 
          CI: true
        run: npm ci